# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


############################################################################
#############################  Build net 6.0 ###############################
############################################################################


- task: DotNetCoreCLI@2
  displayName: Build DFe.Classes net 6.0
  inputs:
    command: 'build'
    projects: './DFe.Classes/DFe.Classes.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build DFe.Utils net 6.0
  inputs:
    command: 'build'
    projects: './DFe.Utils/DFe.Utils.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build DFe.Wsdl net 6.0
  inputs:
    command: 'build'
    projects: './DFe.Wsdl/DFe.Wsdl.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Classes net 6.0
  inputs:
    command: 'build'
    projects: './NFe.Classes/NFe.Classes.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Servicos net 6.0
  inputs:
    command: 'build'
    projects: './NFe.Servicos/NFe.Servicos.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Utils net 6.0
  inputs:
    command: 'build'
    projects: './NFe.Utils/NFe.Utils.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Wsdl net 6.0
  inputs:
    command: 'build'
    projects: './NFe.Wsdl.Standard/NFe.Wsdl.Standard.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Danfe.Fast net 6.0
  inputs:
    command: 'build'
    projects: './NFe.Danfe.Fast/NFe.Danfe.Fast.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build MDFe.Classes net 6.0
  inputs:
    command: 'build'
    projects: './MDFe.Classes/MDFe.Classes.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build MDFe.Utils net 6.0
  inputs:
    command: 'build'
    projects: './MDFe.Utils/MDFe.Utils.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build MDFe.Wsdl net 6.0
  inputs:
    command: 'build'
    projects: './MDFe.Wsdl/MDFe.Wsdl.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build MDFe.Servicos net 6.0
  inputs:
    command: 'build'
    projects: './MDFe.Servicos/MDFe.Servicos.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build CTe.Classes net 6.0
  inputs:
    command: 'build'
    projects: './CTe.Classes/CTe.Classes.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build CTe.Utils net 6.0
  inputs:
    command: 'build'
    projects: './CTe.Utils/CTe.Utils.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build CTe.Wsdl net 6.0
  inputs:
    command: 'build'
    projects: './CTe.Wsdl/CTe.Wsdl.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build CTe.Servicos net 6.0
  inputs:
    command: 'build'
    projects: './CTe.Servicos/CTe.Servicos.csproj'
    arguments: '--no-restore -f net6.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

############################################################################
########################  Build net Standard 2.0 ###########################
############################################################################

- task: DotNetCoreCLI@2
  displayName: Build DFe.Classes net standard 2.0
  inputs:
    command: 'build'
    projects: './DFe.Classes/DFe.Classes.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build DFe.Utils net standard 2.0
  inputs:
    command: 'build'
    projects: './DFe.Utils/DFe.Utils.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build DFe.Wsdl net standard 2.0
  inputs:
    command: 'build'
    projects: './DFe.Wsdl/DFe.Wsdl.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Classes net standard 2.0
  inputs:
    command: 'build'
    projects: './NFe.Classes/NFe.Classes.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Servicos net standard 2.0
  inputs:
    command: 'build'
    projects: './NFe.Servicos/NFe.Servicos.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Utils net standard 2.0
  inputs:
    command: 'build'
    projects: './NFe.Utils/NFe.Utils.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Wsdl net standard 2.0
  inputs:
    command: 'build'
    projects: './NFe.Wsdl.Standard/NFe.Wsdl.Standard.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build NFe.Danfe.Fast net standard 2.0
  inputs:
    command: 'build'
    projects: './NFe.Danfe.Fast/NFe.Danfe.Fast.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build MDFe.Classes net standard 2.0
  inputs:
    command: 'build'
    projects: './MDFe.Classes/MDFe.Classes.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build MDFe.Utils net standard 2.0
  inputs:
    command: 'build'
    projects: './MDFe.Utils/MDFe.Utils.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build MDFe.Wsdl net standard 2.0
  inputs:
    command: 'build'
    projects: './MDFe.Wsdl/MDFe.Wsdl.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build MDFe.Servicos net standard 2.0
  inputs:
    command: 'build'
    projects: './MDFe.Servicos/MDFe.Servicos.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build CTe.Classes net standard 2.0
  inputs:
    command: 'build'
    projects: './CTe.Classes/CTe.Classes.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build CTe.Utils net standard 2.0
  inputs:
    command: 'build'
    projects: './CTe.Utils/CTe.Utils.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build CTe.Wsdl net standard 2.0
  inputs:
    command: 'build'
    projects: './CTe.Wsdl/CTe.Wsdl.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build CTe.Servicos net standard 2.0
  inputs:
    command: 'build'
    projects: './CTe.Servicos/CTe.Servicos.csproj'
    arguments: '--no-restore -f netstandard2.0 -c "Release"'
    workingDirectory: '$(Build.SourcesDirectory)'


###############################################################################
########################  Geração dos pacotes nupkg ###########################
###############################################################################


- task: NuGetCommand@2
  displayName: Gera Pacote Zeus.OpenLine.Net.NFe.NFCe
  inputs:
    command: 'pack'
    packagesToPack: './DFe.NET/NuGet/nfenfcedll/Zeus.Net.NFe.NFCe.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)/Zeus.OpenLine.Net.NFe.NFCe.nupkg'
    versioningScheme: 'off'
    basePath: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Zeus.OpenLine.Net.NFe.NFCe.nupkg'
    ArtifactName: 'zeus.dfe'
    publishLocation: 'Container'
