name: .NET

on:
  push:
    branches: [ tests ]
  pull_request:
    branches: [ tests ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: DFe.NET
        Available Options: warn
        retention-days: 1
